apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-notification
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    component: notification
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    component: notification
