apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-recurring
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.recurring.service.type }}
  ports:
    - port: {{ .Values.recurring.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: {{ include "todo-app.name" . }}
    component: recurring
